# nome da aplicação e porta do servidor
spring.application.name=auth-service
server.port=8081

# configurações do Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# configurações do jdbc/postgres
spring.datasource.url=jdbc:postgresql://localhost:5434/clinica_auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA)
# 'update': Atualiza o schema do banco se a Entidade Java mudar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# propriedade customizada do JWT (utilizada no TokenService)
api.security.token.secret=chaveSecretaJWT

